### ISSUE TITLE
scarlin90's checklist

### ISSUE THREAD

**Issue by scarlin90** [githubteacher/dev-feb-2017#12]
- [x] Create Issue
- [x] Create a branch
- [x] Create some commits
- [x] Create a pull request
- [x] Merge our pull request
