### ISSUE TITLE
robertrankin's checklist

### ISSUE THREAD

**Issue by robertrankin** [githubteacher/dev-feb-2017#13]
- [x] Create an issue
- [x] Create a branch
- [x] Make some commits
- [x] Create a pull request
- [x] Merge our pull request
- [x] Have a great time!

**Comment by scarlin90** [comment]
Have a great time... eh?

**Comment by JohnTresadern** [comment]
Do some more work (if that's even possible!)
