### ISSUE TITLE
barrypowellpulsant's checklist

### ISSUE THREAD

**Issue by barrypowellpulsant** [githubteacher/dev-feb-2017#14]
- [ ] Create an issue
- [ ] Crate a branch
- [ ] Make some commits
- [ ] Create a Pull Request
- [ ] Merge our Pull Request
- [ ] Have a good time?
