### ISSUE TITLE
unixdaddy's checklist

### ISSUE THREAD

**Issue by unixdaddy** [githubteacher/dev-feb-2017#15]
- [ ] Create an Issue
- [ ] Create a branch
- [ ] Make some comments
- [ ] Create a Pull Request
- [ ] Merge our Pull Request
- [ ] Have a GREAT Time?

**Comment by unixdaddy** [comment]
time for 🍺  and then 🛏
