### ISSUE TITLE
EricSlusarz's checklist Gitssues

### ISSUE THREAD

**Issue by ghost** [githubteacher/dev-feb-2017#17]
- [ ] Create an issue
- [ ] create a branch
- [ ] Make some Commits
- [ ] Create a Pull Request
- [ ] Merge our Pull Request
- [ ] Have a good time?

to go **bold** ly
_italics_
-bullet
1.one
1.two
1.three
