### ISSUE TITLE
jlm2112 's checklist

### ISSUE THREAD

**Issue by jlm2112** [githubteacher/dev-feb-2017#18]
- [ ] Create an issue
- [ ] Create a branch
- [ ] Make pull commits
- [ ] Create a pull request
- [ ] Merge our pull request 
- [ ] Have a good time?
