### ISSUE TITLE
orion303s checklist

### ISSUE THREAD

**Issue by orion303** [githubteacher/dev-feb-2017#2]
- [ ] Create and issue
- [x] Create a branch
- [ ] Make some commits
- [x] Create a pull request
- [x] Have a goodun?

**Comment by orion303** [comment]
yo
