### ISSUE TITLE
odimko's checklist

### ISSUE THREAD

**Issue by odimko** [githubteacher/dev-feb-2017#20]
- [x] Create an issue
- [x] Create a branch
- [x] Make some Commits
- [x] Create a Pull Request
- [x] Merge a Pull Request
- [x] Have a great time!
