### ISSUE TITLE
monicasilvestre's checklist

### ISSUE THREAD

**Issue by monicasilvestre** [githubteacher/dev-feb-2017#21]
- [x] Create an issue
- [ ] Create a Branch
- [ ] Make some Commits
- [ ] Create a Pull request
- [ ] Merge or pull request
- [ ] Have a good time
