### ISSUE TITLE
RebeccaVB's checklist

### ISSUE THREAD

**Issue by RebeccaVB** [githubteacher/dev-feb-2017#22]
- [ ] create and issue
- [ ] create a branch
- [ ] Make some commits
- [ ] Create a pull request
- [ ] Merge our Pull request
- [ ] Good Time?
