### ISSUE TITLE
JBWs checklist

### ISSUE THREAD

**Issue by GV-JBW** [githubteacher/dev-feb-2017#23]
- [x] Do a little dance
- [ ] Make a little branch
- [ ] Get down tonight
