### ISSUE TITLE
suresh753's checklist

### ISSUE THREAD

**Issue by suresh753** [githubteacher/dev-feb-2017#24]
- [ ] Create an Issue
- [ ] Create a branch
- [ ] Make some commits
- [ ] Create a pull request
- [ ] Merge our Pull Request
- [ ] Have a good time?
