### ISSUE TITLE
mawer's checklist

### ISSUE THREAD

**Issue by ghost** [githubteacher/dev-feb-2017#27]
- [ ] Create an Issue
- [ ] Create a branch
- [ ] Make some commits
- [ ] Create a Pull Request
- [ ] Merge our Pull Request
