### ISSUE TITLE
ninaddaudkhane's checklist

### ISSUE THREAD

**Issue by ninaddaudkhane** [githubteacher/dev-feb-2017#28]
- [x] Create an Issue
- [ ] Create a Branch
- [ ] Make some Commits
- [ ] Create a Pull Request
- [ ] Merge our Pull Request
- [ ] Have a good time
