### ISSUE TITLE
techkrish's checklist

### ISSUE THREAD

**Issue by techkrish** [githubteacher/dev-feb-2017#3]
- [x] Create an issue
- [ ] Create a branch
- [ ] Make some commits
- [ ] Create a Pull Request
- [ ] Merge our Pull Request
- [ ] Wrap up and summary
