### ISSUE TITLE
Sri55's checklist

### ISSUE THREAD

**Issue by Sri55** [githubteacher/dev-feb-2017#37]
- [ ] Create an Issue
- [ ] Create a Branch
- [ ] Make some commits
- [ ] Create a Pull Request
- [ ] Merge our Request
- [ ] Have a good time?
