### ISSUE TITLE
akczay's checklist

### ISSUE THREAD

**Issue by samet-akcay** [githubteacher/dev-feb-2017#39]
- [ ] Create an Issue
- [ ]  Create a Branch
- [ ] Make some Commits
- [ ] Create a Pull Request
- [ ] Merge a Pull Request
- [ ] Watch Champions League tonight
