### ISSUE TITLE
annalore's checklist

### ISSUE THREAD

**Issue by annalore** [githubteacher/dev-feb-2017#4]
- [x] Create an issue
- [x] Create a branch
- [x] Make some commits
- [x] Create a pull request
- [x] Merge our pull request
- [ ] Have a good time?
