### ISSUE TITLE
my checklist

### ISSUE THREAD

**Issue by dukeovdsea** [githubteacher/dev-feb-2017#40]
- [x] create an issue

- [ ] create a branch

- [ ] make some commit

- [ ] create a pull request

- [ ] merge the pull request

- [ ] had a goodtime
