### ISSUE TITLE
aisruss's checklist

### ISSUE THREAD

**Issue by aisruss** [githubteacher/dev-feb-2017#5]
- [x] Create an Issue
- [x] Create a Branch 
- [x] Make some Commits
- [x] Create a Pull Request
- [x] Merge the Pull Request
- [x] Dance, Magic Dance!
