### ISSUE TITLE
paluchas'checklist

### ISSUE THREAD

**Issue by paluchas** [githubteacher/dev-feb-2017#6]
- [x] Create an Issue
- [x] Create a Branch
- [x] Make some Commits
- [x] Create a Pull Request
- [x] Merge our Pull Request
- [x] Hae a good time?

**Comment by paluchas** [comment]
Great time, great training session.
