### ISSUE TITLE
cshawnbrown checklist

### ISSUE THREAD

**Issue by cshawnbrown** [githubteacher/dev-feb-2017#7]
- [x] Create an Issue
- [x] Create a Branch
- [x] Make some Commits
- [x] Create a Pull Request
- [x] Merge a Pull Request
- [ ] Have a good time
