### ISSUE TITLE
adamclarke88's checklist

### ISSUE THREAD

**Issue by adamclarke88** [githubteacher/dev-feb-2017#81]
- [ ] Create an Issue
 - [ ] Create a Branch
 - [ ] Make some Commits
 - [ ] Create a Pull Request
 - [ ] Merge a Pull Request
 - [ ] Have a good time
