### ISSUE TITLE
cliftoncarvalho's checklist

### ISSUE THREAD

**Issue by clifton-carvalho-ivp** [githubteacher/dev-feb-2017#9]
- [x] Create an issue
- [x] Create a Branch
- [x] Make some Commits
- [x] Create a Pull Request
- [x] Merge our Pull Request
- [x] Peace out

**Comment by clifton-carvalho-ivp** [comment]
Done with the checklist
